name: Matrix output test
on:
  push:
    branches:
      - "*"

jobs:
  prepare:
    outputs:
      networks: ${{ steps.prepare.outptus.networks }}
    runs-on: ubuntu-latest
    steps:
      - name: output prepare
        id: prepare
        run: echo "::set-output name=networks::TEST"
  matrix:
    needs: [prepare]
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ toJSON(steps) }}
    strategy:
      fail-fast: true
      matrix:
        node: [10, 12, 14]
    steps:
      - name: output matrix
        id: matrix
        run: |
          echo "demo node ${{ matrix.node }}" > test.txt
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.node}}
          path: test.txt
          retention-days: 1
  conclude:
    needs: [matrix]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - name: Conclude
        run: ls -R
