name: Pull Request Review Request Added
on:
  pull_request:
    types:
      - review_requested

jobs:
  review-requested:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get comment body
        id: get-comment-body
        run: |
          body="$(cat .github/templates/reviewer_template.md)"
          body=$(sed 's/#USERNAME/@${{ github.event.requested_reviewer.login }}/' <<< "$body")
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get-comment-body.outputs.body }}