name: Pull Request Review
on:
  pull_request:
    types:
      - review_requested
      - review_request_removed

jobs:
  review-requested:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get comment body
        id: get-comment-body
        run: |
          body="$(cat .github/templates/reviewer_template.md)"
          body=$(sed 's/#USERNAME/@${{ github.event.requested_reviewer.login }}/' <<< "$body")
          echo "::set-output name=body::$body"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 1
          body: ${{ steps.get-comment-body.outputs.body }}

