name: Pull Request Review
on:
  pull_request:
    types:
      - review_requested
      - review_request_removed

jobs:
  review-requested:
    runs-on: ubuntu-latest
    steps:
      - name: PR Comment
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(JSON.stringify(context));
            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '[ ] Test'
            })

